apiVersion: v1
kind: PersesDashboard
metadata:
  name: performance-statistics
  project: vllm
spec:
  display:
    name: vLLM Performance Statistics

  variables:
    - kind: ListVariable
      spec:
        display:
          name: Model
          hidden: false
        name: model_name
        allowAllValue: true
        allowMultiple: true
        defaultValue:
          - $__all
        sort: alphabetical-asc
        plugin:
          kind: PrometheusLabelValuesVariable
          spec:
            datasource:
              kind: PrometheusDatasource
              name: prometheus
            labelName: model_name
            matchers:
              - vllm:generation_tokens_total{}

  panels:
    # ===== E2E LATENCY =====
    "e2e_latency_chart":
      kind: Panel
      spec:
        display:
          name: End-to-End Latency Over Time (Average)
        plugin:
          kind: TimeSeriesChart
          spec:
            legend:
              mode: table
              position: bottom
        queries:
          - kind: TimeSeriesQuery
            spec:
              plugin:
                kind: PrometheusTimeSeriesQuery
                spec:
                  datasource:
                    kind: PrometheusDatasource
                    name: prometheus
                  query: |
                    sum by (model_name) (rate(vllm:e2e_request_latency_seconds_sum{model_name=~"$model_name"}[5m]))
                    /
                    sum by (model_name) (rate(vllm:e2e_request_latency_seconds_count{model_name=~"$model_name"}[5m]))
                  seriesNameFormat: '{{model_name}}'

    "e2e_latency_avg":
      kind: Panel
      spec:
        display:
          name: E2E Latency (Average)
        plugin:
          kind: StatChart
          spec:
            calculation: last-number
            format:
              unit: seconds
        queries:
          - kind: TimeSeriesQuery
            spec:
              plugin:
                kind: PrometheusTimeSeriesQuery
                spec:
                  datasource:
                    kind: PrometheusDatasource
                    name: prometheus
                  query: |
                    sum(increase(vllm:e2e_request_latency_seconds_sum{model_name=~"$model_name"}[5m]))
                    /
                    sum(increase(vllm:e2e_request_latency_seconds_count{model_name=~"$model_name"}[5m]))

    "e2e_latency_p50":
      kind: Panel
      spec:
        display:
          name: E2E Latency (P50)
        plugin:
          kind: StatChart
          spec:
            calculation: last-number
            format:
              unit: seconds
        queries:
          - kind: TimeSeriesQuery
            spec:
              plugin:
                kind: PrometheusTimeSeriesQuery
                spec:
                  datasource:
                    kind: PrometheusDatasource
                    name: prometheus
                  query: |
                    histogram_quantile(
                      0.50,
                      sum by (le, model_name) (
                        rate(vllm:e2e_request_latency_seconds_bucket{model_name=~"$model_name"}[5m])
                      )
                    )

    "e2e_latency_p95":
      kind: Panel
      spec:
        display:
          name: E2E Latency (P95)
        plugin:
          kind: StatChart
          spec:
            calculation: last-number
            format:
              unit: seconds
        queries:
          - kind: TimeSeriesQuery
            spec:
              plugin:
                kind: PrometheusTimeSeriesQuery
                spec:
                  datasource:
                    kind: PrometheusDatasource
                    name: prometheus
                  query: |
                    histogram_quantile(
                      0.95,
                      sum by (le, model_name) (
                        rate(vllm:e2e_request_latency_seconds_bucket{model_name=~"$model_name"}[5m])
                      )
                    )

    # ===== TIME TO FIRST TOKEN (TTFT) =====
    "ttft_chart":
      kind: Panel
      spec:
        display:
          name: Time to First Token Over Time (Average)
        plugin:
          kind: TimeSeriesChart
          spec:
            legend:
              mode: table
              position: bottom
        queries:
          - kind: TimeSeriesQuery
            spec:
              plugin:
                kind: PrometheusTimeSeriesQuery
                spec:
                  datasource:
                    kind: PrometheusDatasource
                    name: prometheus
                  query: |
                    sum by (model_name) (rate(vllm:time_to_first_token_seconds_sum{model_name=~"$model_name"}[5m]))
                    /
                    sum by (model_name) (rate(vllm:time_to_first_token_seconds_count{model_name=~"$model_name"}[5m]))
                  seriesNameFormat: '{{model_name}}'

    "ttft_avg":
      kind: Panel
      spec:
        display:
          name: TTFT (Average)
        plugin:
          kind: StatChart
          spec:
            calculation: last-number
            format:
              unit: seconds
        queries:
          - kind: TimeSeriesQuery
            spec:
              plugin:
                kind: PrometheusTimeSeriesQuery
                spec:
                  datasource:
                    kind: PrometheusDatasource
                    name: prometheus
                  query: |
                    sum(increase(vllm:time_to_first_token_seconds_sum{model_name=~"$model_name"}[5m]))
                    /
                    sum(increase(vllm:time_to_first_token_seconds_count{model_name=~"$model_name"}[5m]))

    "ttft_p50":
      kind: Panel
      spec:
        display:
          name: TTFT (P50)
        plugin:
          kind: StatChart
          spec:
            calculation: last-number
            format:
              unit: seconds
        queries:
          - kind: TimeSeriesQuery
            spec:
              plugin:
                kind: PrometheusTimeSeriesQuery
                spec:
                  datasource:
                    kind: PrometheusDatasource
                    name: prometheus
                  query: |
                    histogram_quantile(
                      0.50,
                      sum by (le, model_name) (
                        rate(vllm:time_to_first_token_seconds_bucket{model_name=~"$model_name"}[5m])
                      )
                    )

    "ttft_p95":
      kind: Panel
      spec:
        display:
          name: TTFT (P95)
        plugin:
          kind: StatChart
          spec:
            calculation: last-number
            format:
              unit: seconds
        queries:
          - kind: TimeSeriesQuery
            spec:
              plugin:
                kind: PrometheusTimeSeriesQuery
                spec:
                  datasource:
                    kind: PrometheusDatasource
                    name: prometheus
                  query: |
                    histogram_quantile(
                      0.95,
                      sum by (le, model_name) (
                        rate(vllm:time_to_first_token_seconds_bucket{model_name=~"$model_name"}[5m])
                      )
                    )

    # ===== TIME PER OUTPUT TOKEN (TPOT / ITL) =====
    "tpot_chart":
      kind: Panel
      spec:
        display:
          name: Time per Output Token Over Time
        plugin:
          kind: TimeSeriesChart
          spec:
            legend:
              mode: table
              position: bottom
        queries:
          - kind: TimeSeriesQuery
            spec:
              plugin:
                kind: PrometheusTimeSeriesQuery
                spec:
                  datasource:
                    kind: PrometheusDatasource
                    name: prometheus
                  query: |
                    sum by (model_name) (rate(vllm:request_time_per_output_token_seconds_sum{model_name=~"$model_name"}[5m]))
                    /
                    sum by (model_name) (rate(vllm:request_time_per_output_token_seconds_count{model_name=~"$model_name"}[5m]))
                  seriesNameFormat: '{{model_name}} avg'
          - kind: TimeSeriesQuery
            spec:
              plugin:
                kind: PrometheusTimeSeriesQuery
                spec:
                  datasource:
                    kind: PrometheusDatasource
                    name: prometheus
                  query: |
                    histogram_quantile(
                      0.50,
                      sum by (le, model_name) (
                        rate(vllm:request_time_per_output_token_seconds_bucket{model_name=~"$model_name"}[5m])
                      )
                    )
                  seriesNameFormat: '{{model_name}} p50'
          - kind: TimeSeriesQuery
            spec:
              plugin:
                kind: PrometheusTimeSeriesQuery
                spec:
                  datasource:
                    kind: PrometheusDatasource
                    name: prometheus
                  query: |
                    histogram_quantile(
                      0.95,
                      sum by (le, model_name) (
                        rate(vllm:request_time_per_output_token_seconds_bucket{model_name=~"$model_name"}[5m])
                      )
                    )
                  seriesNameFormat: '{{model_name}} p95'

    "tpot_avg":
      kind: Panel
      spec:
        display:
          name: TPOT (Average)
        plugin:
          kind: StatChart
          spec:
            calculation: last-number
            format:
              unit: seconds
        queries:
          - kind: TimeSeriesQuery
            spec:
              plugin:
                kind: PrometheusTimeSeriesQuery
                spec:
                  datasource:
                    kind: PrometheusDatasource
                    name: prometheus
                  query: |
                    sum(increase(vllm:request_time_per_output_token_seconds_sum{model_name=~"$model_name"}[5m]))
                    /
                    sum(increase(vllm:request_time_per_output_token_seconds_count{model_name=~"$model_name"}[5m]))

    "tpot_p50":
      kind: Panel
      spec:
        display:
          name: TPOT (P50)
        plugin:
          kind: StatChart
          spec:
            calculation: last-number
            format:
              unit: seconds
        queries:
          - kind: TimeSeriesQuery
            spec:
              plugin:
                kind: PrometheusTimeSeriesQuery
                spec:
                  datasource:
                    kind: PrometheusDatasource
                    name: prometheus
                  query: |
                    histogram_quantile(
                      0.50,
                      sum by (le, model_name) (
                        rate(vllm:request_time_per_output_token_seconds_bucket{model_name=~"$model_name"}[5m])
                      )
                    )

    "tpot_p95":
      kind: Panel
      spec:
        display:
          name: TPOT (P95)
        plugin:
          kind: StatChart
          spec:
            calculation: last-number
            format:
              unit: seconds
        queries:
          - kind: TimeSeriesQuery
            spec:
              plugin:
                kind: PrometheusTimeSeriesQuery
                spec:
                  datasource:
                    kind: PrometheusDatasource
                    name: prometheus
                  query: |
                    histogram_quantile(
                      0.95,
                      sum by (le, model_name) (
                        rate(vllm:request_time_per_output_token_seconds_bucket{model_name=~"$model_name"}[5m])
                      )
                    )

    # ===== THROUGHPUT =====
    "throughput_chart":
      kind: Panel
      spec:
        display:
          name: Token Throughput (tokens/sec)
        plugin:
          kind: TimeSeriesChart
          spec:
            legend:
              mode: table
              position: bottom
        queries:
          - kind: TimeSeriesQuery
            spec:
              plugin:
                kind: PrometheusTimeSeriesQuery
                spec:
                  datasource:
                    kind: PrometheusDatasource
                    name: prometheus
                  query: |
                    sum by (model_name) (rate(vllm:generation_tokens_total{model_name=~"$model_name"}[5m]))
                  seriesNameFormat: '{{model_name}} output tokens'
          - kind: TimeSeriesQuery
            spec:
              plugin:
                kind: PrometheusTimeSeriesQuery
                spec:
                  datasource:
                    kind: PrometheusDatasource
                    name: prometheus
                  query: |
                    sum by (model_name) (rate(vllm:prompt_tokens_total{model_name=~"$model_name"}[5m]))
                  seriesNameFormat: '{{model_name}} input tokens'

    "request_rate":
      kind: Panel
      spec:
        display:
          name: Request Rate (req/sec)
        plugin:
          kind: TimeSeriesChart
          spec:
            legend:
              mode: table
              position: bottom
        queries:
          - kind: TimeSeriesQuery
            spec:
              plugin:
                kind: PrometheusTimeSeriesQuery
                spec:
                  datasource:
                    kind: PrometheusDatasource
                    name: prometheus
                  query: |
                    sum by (model_name) (rate(vllm:request_success_total{model_name=~"$model_name"}[5m]))
                  seriesNameFormat: '{{model_name}}'

    # ===== RESOURCE UTILIZATION =====
    "kv_cache":
      kind: Panel
      spec:
        display:
          name: KV Cache Usage (%)
        plugin:
          kind: TimeSeriesChart
          spec:
            legend:
              mode: table
              position: bottom
        queries:
          - kind: TimeSeriesQuery
            spec:
              plugin:
                kind: PrometheusTimeSeriesQuery
                spec:
                  datasource:
                    kind: PrometheusDatasource
                    name: prometheus
                  query: |
                    avg by (model_name) (vllm:kv_cache_usage_perc{model_name=~"$model_name"}) * 100
                  seriesNameFormat: '{{model_name}}'

    "running_requests":
      kind: Panel
      spec:
        display:
          name: Running Requests
        plugin:
          kind: TimeSeriesChart
          spec:
            legend:
              mode: table
              position: bottom
        queries:
          - kind: TimeSeriesQuery
            spec:
              plugin:
                kind: PrometheusTimeSeriesQuery
                spec:
                  datasource:
                    kind: PrometheusDatasource
                    name: prometheus
                  query: |
                    sum by (model_name) (vllm:num_requests_running{model_name=~"$model_name"})
                  seriesNameFormat: '{{model_name}}'

    "waiting_requests":
      kind: Panel
      spec:
        display:
          name: Waiting Requests
        plugin:
          kind: TimeSeriesChart
          spec:
            legend:
              mode: table
              position: bottom
        queries:
          - kind: TimeSeriesQuery
            spec:
              plugin:
                kind: PrometheusTimeSeriesQuery
                spec:
                  datasource:
                    kind: PrometheusDatasource
                    name: prometheus
                  query: |
                    sum by (model_name) (vllm:num_requests_waiting{model_name=~"$model_name"})
                  seriesNameFormat: '{{model_name}}'

  layouts:
    - kind: Grid
      spec:
        display:
          title: End-to-End Latency
        items:
          - x: 0
            y: 0
            width: 12
            height: 6
            content: { $ref: '#/spec/panels/e2e_latency_chart' }
          - x: 12
            y: 0
            width: 4
            height: 3
            content: { $ref: '#/spec/panels/e2e_latency_avg' }
          - x: 16
            y: 0
            width: 4
            height: 3
            content: { $ref: '#/spec/panels/e2e_latency_p50' }
          - x: 20
            y: 0
            width: 4
            height: 3
            content: { $ref: '#/spec/panels/e2e_latency_p95' }

    - kind: Grid
      spec:
        display:
          title: Time to First Token (TTFT)
        items:
          - x: 0
            y: 6
            width: 12
            height: 6
            content: { $ref: '#/spec/panels/ttft_chart' }
          - x: 12
            y: 6
            width: 4
            height: 3
            content: { $ref: '#/spec/panels/ttft_avg' }
          - x: 16
            y: 6
            width: 4
            height: 3
            content: { $ref: '#/spec/panels/ttft_p50' }
          - x: 20
            y: 6
            width: 4
            height: 3
            content: { $ref: '#/spec/panels/ttft_p95' }

    - kind: Grid
      spec:
        display:
          title: Time per Output Token (TPOT)
        items:
          - x: 0
            y: 12
            width: 12
            height: 6
            content: { $ref: '#/spec/panels/tpot_chart' }
          - x: 12
            y: 12
            width: 4
            height: 3
            content: { $ref: '#/spec/panels/tpot_avg' }
          - x: 16
            y: 12
            width: 4
            height: 3
            content: { $ref: '#/spec/panels/tpot_p50' }
          - x: 20
            y: 12
            width: 4
            height: 3
            content: { $ref: '#/spec/panels/tpot_p95' }

    - kind: Grid
      spec:
        display:
          title: Throughput & Request Rate
        items:
          - x: 0
            y: 18
            width: 12
            height: 6
            content: { $ref: '#/spec/panels/throughput_chart' }
          - x: 12
            y: 18
            width: 12
            height: 6
            content: { $ref: '#/spec/panels/request_rate' }

    - kind: Grid
      spec:
        display:
          title: Resource Utilization
        items:
          - x: 0
            y: 24
            width: 8
            height: 6
            content: { $ref: '#/spec/panels/kv_cache' }
          - x: 8
            y: 24
            width: 8
            height: 6
            content: { $ref: '#/spec/panels/running_requests' }
          - x: 16
            y: 24
            width: 8
            height: 6
            content: { $ref: '#/spec/panels/waiting_requests' }
